"""configuracao e auditoria

Revision ID: 2e0b818e2324
Revises: 966ce889d9f0
Create Date: 2026-07-14 00:10:06.927694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2e0b818e2324'
down_revision: Union[str, None] = '966ce889d9f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('configuracao',
    sa.Column('chave', sa.String(length=60), nullable=False),
    sa.Column('valor', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('chave')
    )
    op.create_table('evento_auditoria',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidato_id', sa.UUID(), nullable=True),
    sa.Column('ator', sa.String(length=20), nullable=False),
    sa.Column('ator_detalhe', sa.String(length=200), nullable=True),
    sa.Column('acao', sa.String(length=60), nullable=False),
    sa.Column('detalhe', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evento_auditoria_acao'), 'evento_auditoria', ['acao'], unique=False)
    op.create_index(op.f('ix_evento_auditoria_candidato_id'), 'evento_auditoria', ['candidato_id'], unique=False)
    op.create_index(op.f('ix_evento_auditoria_criado_em'), 'evento_auditoria', ['criado_em'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evento_auditoria_criado_em'), table_name='evento_auditoria')
    op.drop_index(op.f('ix_evento_auditoria_candidato_id'), table_name='evento_auditoria')
    op.drop_index(op.f('ix_evento_auditoria_acao'), table_name='evento_auditoria')
    op.drop_table('evento_auditoria')
    op.drop_table('configuracao')
    # ### end Alembic commands ###
