"""schema inicial

Revision ID: 41d118293b7e
Revises: 
Create Date: 2026-07-13 23:18:13.304296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '41d118293b7e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidato',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('convidado', 'preenchendo', 'docs_pendentes', 'aguardando_assinatura', 'envio_concluido', 'em_revisao', 'aprovado', 'reprovado_pendencias', 'expurgado', name='status_candidato'), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('celular_whatsapp', sa.String(length=20), nullable=False),
    sa.Column('aceite_lgpd_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('declaracao_veracidade_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_candidato_email'), 'candidato', ['email'], unique=False)
    op.create_table('usuario_rh',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.Column('senha_hash', sa.String(length=300), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuario_rh_email'), 'usuario_rh', ['email'], unique=True)
    op.create_table('acesso_magico',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expira_em', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revogado', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acesso_magico_candidato_id'), 'acesso_magico', ['candidato_id'], unique=False)
    op.create_index(op.f('ix_acesso_magico_token_hash'), 'acesso_magico', ['token_hash'], unique=True)
    op.create_table('contato_emergencia',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('ordem', sa.SmallInteger(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('parentesco', sa.String(length=60), nullable=False),
    sa.Column('telefone_celular', sa.String(length=20), nullable=False),
    sa.Column('telefone_fixo_endereco', sa.String(length=300), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contato_emergencia_candidato_id'), 'contato_emergencia', ['candidato_id'], unique=False)
    op.create_table('dados_pessoais',
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=True),
    sa.Column('sexo', sa.Enum('feminino', 'masculino', name='sexo'), nullable=True),
    sa.Column('identidade_genero', sa.Enum('cisgenero', 'transgenero', 'transexual', 'travesti', 'genero_fluido', 'agenero', 'nao_informar', name='identidade_genero'), nullable=True),
    sa.Column('cor_raca', sa.Enum('branca', 'preta', 'parda', 'amarela', 'indigena', name='cor_raca'), nullable=True),
    sa.Column('nacionalidade', sa.Enum('brasileira', 'estrangeira', name='nacionalidade'), nullable=True),
    sa.Column('naturalidade_cidade', sa.String(length=120), nullable=True),
    sa.Column('naturalidade_uf', sa.String(length=2), nullable=True),
    sa.Column('estado_civil', sa.Enum('solteiro', 'casado', 'uniao_estavel', 'divorciado', 'separado', 'viuvo', name='estado_civil'), nullable=True),
    sa.Column('escolaridade', sa.Enum('fund_incompleto', 'fund_completo', 'medio_incompleto', 'medio_completo', 'sup_incompleto', 'sup_completo', 'pos_graduacao', name='escolaridade'), nullable=True),
    sa.Column('pcd', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('candidato_id')
    )
    op.create_table('dados_profissionais_bancarios',
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('tamanho_calca', sa.String(length=10), nullable=True),
    sa.Column('tamanho_camisa', sa.String(length=10), nullable=True),
    sa.Column('tamanho_calcado', sa.String(length=10), nullable=True),
    sa.Column('banco', sa.String(length=120), nullable=True),
    sa.Column('pix_tipo', sa.Enum('cpf', 'celular', 'email', 'aleatoria', name='tipo_chave_pix'), nullable=True),
    sa.Column('pix_chave', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('candidato_id')
    )
    op.create_table('dependente',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('nome_completo', sa.String(length=200), nullable=False),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('parentesco', sa.Enum('conjuge', 'filho', 'menor_guarda', name='parentesco'), nullable=False),
    sa.Column('deduz_irrf', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dependente_candidato_id'), 'dependente', ['candidato_id'], unique=False)
    op.create_table('documentos_identificacao',
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('rg_numero', sa.String(length=20), nullable=True),
    sa.Column('rg_orgao_emissor', sa.String(length=40), nullable=True),
    sa.Column('rg_data_expedicao', sa.Date(), nullable=True),
    sa.Column('cpf', sa.String(length=11), nullable=True),
    sa.Column('pis_nis_pasep', sa.String(length=14), nullable=True),
    sa.Column('cnh_numero', sa.String(length=20), nullable=True),
    sa.Column('cnh_categoria', sa.String(length=5), nullable=True),
    sa.Column('titulo_eleitor_numero', sa.String(length=14), nullable=True),
    sa.Column('titulo_eleitor_zona', sa.String(length=6), nullable=True),
    sa.Column('titulo_eleitor_secao', sa.String(length=6), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('candidato_id')
    )
    op.create_table('endereco',
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('cep', sa.String(length=8), nullable=True),
    sa.Column('logradouro_numero_complemento', sa.String(length=300), nullable=True),
    sa.Column('bairro', sa.String(length=120), nullable=True),
    sa.Column('cidade', sa.String(length=120), nullable=True),
    sa.Column('uf', sa.String(length=2), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('candidato_id')
    )
    op.create_table('ficha_emergencia',
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('tipo_sanguineo', sa.String(length=4), nullable=True),
    sa.Column('usa_medicamento_continuo', sa.Boolean(), nullable=True),
    sa.Column('medicamentos', sa.Text(), nullable=True),
    sa.Column('condicoes_medicas', sa.Text(), nullable=True),
    sa.Column('orientacao_emergencia', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('candidato_id')
    )
    op.create_table('vale_transporte',
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('optante', sa.Boolean(), nullable=True),
    sa.Column('cartao_dftrans', sa.String(length=40), nullable=True),
    sa.Column('trajeto_descricao', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('candidato_id')
    )
    op.create_table('slot_documento',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('tipo', sa.Enum('foto_3x4', 'rg', 'cpf_doc', 'ctps_digital', 'pis_comprovante', 'titulo_eleitor_doc', 'reservista', 'habilitacao_prof', 'laudo_pcd', 'comp_endereco', 'comp_escolaridade', 'diplomas', 'nada_consta_eleitoral', 'nada_consta_criminal', 'cert_casamento', 'cert_nascimento_dep', 'cartao_vacina_dep', 'declaracao_escolar_dep', 'cartao_vt', name='tipo_documento'), nullable=False),
    sa.Column('dependente_id', sa.UUID(), nullable=True),
    sa.Column('obrigatorio', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('pendente', 'enviado', 'aprovado', 'rejeitado', 'dispensado', name='status_slot'), nullable=False),
    sa.Column('motivo_rejeicao', sa.Enum('ilegivel', 'doc_errado', 'vencido', 'incompleto', 'outro', name='motivo_rejeicao'), nullable=True),
    sa.Column('motivo_rejeicao_obs', sa.Text(), nullable=True),
    sa.Column('arquivo_original_key', sa.String(length=300), nullable=True),
    sa.Column('arquivo_pdf_key', sa.String(length=300), nullable=True),
    sa.Column('paginas', sa.SmallInteger(), nullable=True),
    sa.Column('enviado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revisado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revisado_por', sa.UUID(), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.ForeignKeyConstraint(['dependente_id'], ['dependente.id'], ),
    sa.ForeignKeyConstraint(['revisado_por'], ['usuario_rh.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slot_documento_candidato_id'), 'slot_documento', ['candidato_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slot_documento_candidato_id'), table_name='slot_documento')
    op.drop_table('slot_documento')
    op.drop_table('vale_transporte')
    op.drop_table('ficha_emergencia')
    op.drop_table('endereco')
    op.drop_table('documentos_identificacao')
    op.drop_index(op.f('ix_dependente_candidato_id'), table_name='dependente')
    op.drop_table('dependente')
    op.drop_table('dados_profissionais_bancarios')
    op.drop_table('dados_pessoais')
    op.drop_index(op.f('ix_contato_emergencia_candidato_id'), table_name='contato_emergencia')
    op.drop_table('contato_emergencia')
    op.drop_index(op.f('ix_acesso_magico_token_hash'), table_name='acesso_magico')
    op.drop_index(op.f('ix_acesso_magico_candidato_id'), table_name='acesso_magico')
    op.drop_table('acesso_magico')
    op.drop_index(op.f('ix_usuario_rh_email'), table_name='usuario_rh')
    op.drop_table('usuario_rh')
    op.drop_index(op.f('ix_candidato_email'), table_name='candidato')
    op.drop_table('candidato')
    # ### end Alembic commands ###
