"""assinaturas

Revision ID: 66a5f1cd51a0
Revises: 41d118293b7e
Create Date: 2026-07-13 23:21:13.437299

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '66a5f1cd51a0'
down_revision: Union[str, None] = '41d118293b7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assinatura',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('candidato_id', sa.UUID(), nullable=False),
    sa.Column('documento', sa.Enum('ficha_cadastro', 'ficha_emergencia', 'termo_vt', name='documento_assinavel'), nullable=False),
    sa.Column('pdf_key', sa.String(length=300), nullable=True),
    sa.Column('hash_sha256', sa.String(length=64), nullable=True),
    sa.Column('otp_hash', sa.String(length=64), nullable=True),
    sa.Column('otp_expira_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('otp_tentativas', sa.Integer(), nullable=False),
    sa.Column('assinado_em', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=400), nullable=True),
    sa.Column('criado_em', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidato_id'], ['candidato.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_assinatura_candidato_id'), 'assinatura', ['candidato_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assinatura_candidato_id'), table_name='assinatura')
    op.drop_table('assinatura')
    # ### end Alembic commands ###
